use std::time::SystemTime;

use crate::databases::osu::primitives::*;

pub struct PartialBeatmap {
    entry_size: Option<i32>,
    artist_name: Option<String>,
    artist_name_unicode: Option<String>,
    song_title: Option<String>,
    song_title_unicode: Option<String>,
    creator_name: Option<String>,
    difficulty: Option<String>,
    audio_file_name: Option<String>,
    md5_beatmap_hash: Option<String>,
    dotosu_file_name: Option<String>,
    ranked_status: Option<RankedStatus>,
    number_of_hitcircles: Option<i16>,
    number_of_sliders: Option<i16>,
    number_of_spinners: Option<i16>,
    last_modification_time: Option<SystemTime>,
    approach_rate: Option<ByteSingle>,
    circle_size: Option<ByteSingle>,
    hp_drain: Option<ByteSingle>,
    overall_difficulty: Option<ByteSingle>,
    slider_velocity: Option<f64>,
    num_mod_combo_star_ratings_standard: Option<i32>,
    mod_combo_star_ratings_standard: Option<Vec<(i32, f64)>>,
    num_mod_combo_star_ratings_taiko: Option<i32>,
    mod_combo_star_ratings_taiko: Option<Vec<(i32, f64)>>,
    num_mod_combo_star_ratings_ctb: Option<i32>,
    mod_combo_star_ratings_ctb: Option<Vec<(i32, f64)>>,
    num_mod_combo_star_ratings_mania: Option<i32>,
    mod_combo_star_ratings_mania: Option<Vec<(i32, f64)>>,
    drain_time: Option<i32>,
    total_time: Option<i32>,
    preview_offset_from_start_ms: Option<i32>,
    num_timing_points: Option<i32>,
    timing_points: Option<Vec<TimingPoint>>,
    beatmap_id: Option<i32>,
    beatmap_set_id: Option<i32>,
    thread_id: Option<i32>,
    standard_grade: Option<u8>,
    taiko_grade: Option<u8>,
    ctb_grade: Option<u8>,
    mania_grade: Option<u8>,
    local_offset: Option<i16>,
    stack_leniency: Option<f32>,
    gameplay_mode: Option<GameplayMode>,
    song_source: Option<String>,
    song_tags: Option<String>,
    online_offset: Option<i16>,
    font_used_for_song_title: Option<String>,
    unplayed: Option<bool>,
    last_played: Option<SystemTime>,
    is_osz2: Option<bool>,
    beatmap_folder_name: Option<String>,
    last_checked_against_repo: Option<SystemTime>,
    ignore_beatmap_sound: Option<bool>,
    ignore_beatmap_skin: Option<bool>,
    disable_storyboard: Option<bool>,
    disable_video: Option<bool>,
    visual_override: Option<bool>,
    unknown_short: Option<i16>,
    offset_from_song_start_in_editor_ms: Option<i32>,
    mania_scroll_speed: Option<u8>
}