use std::io::{Result as IoResult, Error as IoError, ErrorKind::InvalidInput};

use clap::{Arg, App, SubCommand, AppSettings, ArgGroup};
use chrono::naive::NaiveDate;

use crate::load_settings::LoadSetting;
use crate::databases::osu::primitives::{RankedStatus, ByteSingle, GameplayMode};

pub struct BeatmapLoadSettings {
    pub entry_size: LoadSetting<i32>,
    pub artist_name: LoadSetting<Option<String>>,
    pub artist_name_unicode: LoadSetting<Option<String>>,
    pub song_title: LoadSetting<Option<String>>,
    pub song_title_unicode: LoadSetting<Option<String>>,
    pub creator_name: LoadSetting<Option<String>>,
    pub difficulty: LoadSetting<Option<String>>,
    pub audio_file_name: LoadSetting<Option<String>>,
    pub md5_beatmap_hash: LoadSetting<String>,
    pub dotosu_file_name: LoadSetting<Option<String>>,
    pub ranked_status: LoadSetting<RankedStatus>,
    pub number_of_hitcircles: LoadSetting<i16>,
    pub number_of_sliders: LoadSetting<i16>,
    pub number_of_spinners: LoadSetting<i16>,
    pub last_modification_time: LoadSetting<NaiveDate>,
    pub approach_rate: LoadSetting<ByteSingle>,
    pub circle_size: LoadSetting<ByteSingle>,
    pub hp_drain: LoadSetting<ByteSingle>,
    pub overall_difficulty: LoadSetting<ByteSingle>,
    pub slider_velocity: LoadSetting<f64>,
    pub num_mod_combo_star_ratings_standard: LoadSetting<i32>,
    pub num_mod_combo_star_ratings_taiko: LoadSetting<i32>,
    pub num_mod_combo_star_ratings_ctb: LoadSetting<i32>,
    pub num_mod_combo_star_ratings_mania: LoadSetting<i32>,
    pub drain_time: LoadSetting<i32>,
    pub total_time: LoadSetting<i32>,
    pub preview_offset_from_start_ms: LoadSetting<i32>,
    pub num_timing_points: LoadSetting<i32>,
    pub beatmap_id: LoadSetting<i32>,
    pub beatmap_set_id: LoadSetting<i32>,
    pub thread_id: LoadSetting<i32>,
    pub standard_grade: LoadSetting<u8>,
    pub taiko_grade: LoadSetting<u8>,
    pub ctb_grade: LoadSetting<u8>,
    pub mania_grade: LoadSetting<u8>,
    pub local_offset: LoadSetting<i16>,
    pub stack_leniency: LoadSetting<f32>,
    pub gameplay_mode: LoadSetting<GameplayMode>,
    pub song_source: LoadSetting<Option<String>>,
    pub song_tags: LoadSetting<Option<String>>,
    pub online_offset: LoadSetting<i16>,
    pub font_used_for_song_title: LoadSetting<Option<String>>,
    pub unplayed: LoadSetting<bool>,
    pub last_played: LoadSetting<NaiveDate>,
    pub is_osz2: LoadSetting<bool>,
    pub beatmap_folder_name: LoadSetting<Option<String>>,
    pub last_checked_against_repo: LoadSetting<NaiveDate>,
    pub ignore_beatmap_sound: LoadSetting<bool>,
    pub ignore_beatmap_skin: LoadSetting<bool>,
    pub disable_storyboard: LoadSetting<bool>,
    pub disable_video: LoadSetting<bool>,
    pub visual_override: LoadSetting<bool>,
    pub offset_from_song_start_in_editor_ms: LoadSetting<i32>,
    pub mania_scroll_speed: LoadSetting<u8>
}