use std::io::{Result as IoResult, Error as IoError, ErrorKind::InvalidInput};

use clap::{Arg, App, SubCommand, AppSettings, ArgGroup};
use chrono::naive::NaiveDate;

use crate::query::Comparison;
use crate::databases::osu::primitives::{RankedStatus, ByteSingle, GameplayMode};

pub struct BeatmapQuery {
    pub entry_size: Option<Comparison<i32>>,
    pub artist_name: Option<Comparison<String>>,
    pub artist_name_unicode: Option<Comparison<String>>,
    pub song_title: Option<Comparison<String>>,
    pub song_title_unicode: Option<Comparison<String>>,
    pub creator_name: Option<Comparison<String>>,
    pub difficulty: Option<Comparison<String>>,
    pub audio_file_name: Option<Comparison<String>>,
    pub md5_beatmap_hash: Option<Comparison<String>>,
    pub dotosu_file_name: Option<Comparison<String>>,
    pub ranked_status: Option<Comparison<RankedStatus>>,
    pub number_of_hitcircles: Option<Comparison<i16>>,
    pub number_of_sliders: Option<Comparison<i16>>,
    pub number_of_spinners: Option<Comparison<i16>>,
    pub last_modification_time: Option<Comparison<NaiveDate>>,
    pub approach_rate: Option<Comparison<ByteSingle>>,
    pub circle_size: Option<Comparison<ByteSingle>>,
    pub hp_drain: Option<Comparison<ByteSingle>>,
    pub overall_difficulty: Option<Comparison<ByteSingle>>,
    pub slider_velocity: Option<Comparison<f64>>,
    pub num_mod_combo_star_ratings_standard: Option<Comparison<i32>>,
    pub num_mod_combo_star_ratings_taiko: Option<Comparison<i32>>,
    pub num_mod_combo_star_ratings_ctb: Option<Comparison<i32>>,
    pub num_mod_combo_star_ratings_mania: Option<Comparison<i32>>,
    pub drain_time: Option<Comparison<i32>>,
    pub total_time: Option<Comparison<i32>>,
    pub preview_offset_from_start_ms: Option<Comparison<i32>>,
    pub num_timing_points: Option<Comparison<i32>>,
    pub beatmap_id: Option<Comparison<i32>>,
    pub beatmap_set_id: Option<Comparison<i32>>,
    pub thread_id: Option<Comparison<i32>>,
    pub standard_grade: Option<Comparison<u8>>,
    pub taiko_grade: Option<Comparison<u8>>,
    pub ctb_grade: Option<Comparison<u8>>,
    pub mania_grade: Option<Comparison<u8>>,
    pub local_offset: Option<Comparison<i16>>,
    pub stack_leniency: Option<Comparison<f32>>,
    pub gameplay_mode: Option<Comparison<GameplayMode>>,
    pub song_source: Option<Comparison<String>>,
    pub song_tags: Option<Comparison<String>>,
    pub online_offset: Option<Comparison<i16>>,
    pub font_used_for_song_title: Option<Comparison<String>>,
    pub unplayed: Option<Comparison<bool>>,
    pub last_played: Option<Comparison<NaiveDate>>,
    pub is_osz2: Option<Comparison<bool>>,
    pub beatmap_folder_name: Option<Comparison<String>>,
    pub last_checked_against_repo: Option<Comparison<NaiveDate>>,
    pub ignore_beatmap_sound: Option<Comparison<bool>>,
    pub ignore_beatmap_skin: Option<Comparison<bool>>,
    pub disable_storyboard: Option<Comparison<bool>>,
    pub disable_video: Option<Comparison<bool>>,
    pub visual_override: Option<Comparison<bool>>,
    pub offset_from_song_start_in_editor_ms: Option<Comparison<i32>>,
    pub mania_scroll_speed: Option<Comparison<u8>>
}